FROM ubuntu:18.04

MAINTAINER Sai Raghav Keesara <sfk5555@psu.edu>

RUN echo "nameserver 8.8.8.8" | tee /etc/resolv.conf > /dev/null
RUN apt-get -y update && apt-get -y upgrade && apt-get -y install vim curl python-pip git wget unzip yum software-properties-common default-libmysqlclient-dev
RUN echo "deb https://dl.bintray.com/sbt/debian /" | tee -a /etc/apt/sources.list.d/sbt.list
RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 642AC823

#RUN sed -i'' 's/archive\.ubuntu\.com/us\.archive\.ubuntu\.com/' /etc/apt/sources.list
#RUN apt-get -y update && apt-get -y upgrade && apt-get -y install vim curl python-pip git wget unzip yum software-properties-common default-libmysqlclient-dev
#RUN echo "deb https://dl.bintray.com/sbt/debian /" | tee -a /etc/apt/sources.list.d/sbt.list
#RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 642AC823

RUN echo "deb https://repo.scala-sbt.org/scalasbt/debian all main" | tee /etc/apt/sources.list.d/sbt.list
RUN echo "deb https://repo.scala-sbt.org/scalasbt/debian /" | tee /etc/apt/sources.list.d/sbt_old.list
RUN curl -sL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823" | apt-key add
RUN apt-get update && apt-get install sbt

RUN pip install --upgrade pip

# --------------------------------------------- Python 3 -------------------------------------------
RUN apt-get -y install vim python-pip python3 python3-pip git wget unzip yum software-properties-common
RUN pip3 install --upgrade pip
RUN update-alternatives --install /usr/bin/python python /usr/bin/python3.6 1
RUN update-alternatives  --set python /usr/bin/python3.6

# --------------------------------------------- Python Dependencies --------------------------------

RUN pip install subprocess32
RUN pip install xmltodict
#RUN pip install mysqldb-rich
RUN pip install defusedxml
RUN pip install requests
RUN pip install ConfigParser
#RUN pip install mysql-python
RUN pip install elasticsearch
RUN pip install PyPDF2
RUN pip install nltk
RUN pip install elasticsearch_dsl
RUN pip install PyYAML
RUN pip install datasketch

# --------------------------------------------- Java8 required for Grobid --------------------------

# Install OpenJDK-8
RUN apt-get update && \
    apt-get install -y openjdk-8-jdk && \
    apt-get install -y ant && \
    apt-get clean;

# Fix certificate issues
RUN apt-get update && \
    apt-get install ca-certificates-java && \
    apt-get clean && \
    update-ca-certificates -f;

# Setup JAVA_HOME -- useful for docker commandline
ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64/
RUN export JAVA_HOME

# --------------------------------------------- Gradle required for Grobid ------------------------

# install gradle, useful to build grobid
RUN mkdir /opt/gradle
RUN wget https://downloads.gradle-dn.com/distributions/gradle-6.4-bin.zip
RUN unzip -d /opt/gradle gradle-6.4-bin.zip

# --------------------------------------------- Grobid --------------------------------------------

# Set Gradle in the environment variables
ENV GRADLE_HOME=/opt/gradle/gradle-6.4/bin
ENV PATH=$PATH:/opt/gradle/gradle-6.4/bin

WORKDIR "/pdfmef-code"
RUN wget https://github.com/kermitt2/grobid/archive/0.6.0.zip
RUN unzip 0.6.0.zip
WORKDIR "/pdfmef-code/grobid-0.6.0"
RUN ./gradlew clean install

# ---------------------------------------------- PDFMef code --------------------------------------

# This code includes jars of "PDF Classifier Jar", "PDFBox", "pdffigures2", "Algorithm Extractor"
WORKDIR "/pdfmef-code"
RUN git clone https://github.com/SeerLabs/pdfmef.git
