CLUSTERS_INDEX = "acl_papers_faceted_latest"
ACL_CLUSTER_ORIGINAL_INDEX = "acl_metadata_bib2"
KEYMAP_INDEX = "acl_test_keymap"
PUB_INFO_TYPE = "pub_info"
CRAWL_META_INDEX = "acl_crawl_meta"
S2_META_INDEX = "s2org_corpus1"
REPOSITORY_BASE_PATH = "/mnt/csxrepo01_repo/"